# Generated by Django 2.2.4 on 2019-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
